Anaconda Workflow & `meta.yaml`
openscilab/pymilo pull request #105
Opened 2024-05-26 18:10 UTC by sadrasabouri

#### Reference Issues/PRs
#100 

#### What does this implement/fix? Explain your changes.
### Added
- Anaconda workflow
### Changed
- Anaconda installation instruction added to `README.md`
- Package's dependencies added to `meta.yaml`

#### Any other comments?

2024-06-01 00:29 UTC, AHReccese commented
@sadrasabouri LGTM, Thank you so much for your work.
According to this [issue](https://github.com/bridgecrewio/checkov/issues/4127) it seems that the default access is `write-all` and sometimes(as discussed in the thread) in some projects suddenly this warning is getting raised and it is ok, even if you have not changed anything, so, I think it does address questions you raised in the last meeting, I tried to downgrade the workflow's access level from default `write-all` to `read-all` and it is now ok.

2024-06-01 00:29 UTC, AHReccese approved these changes

2024-06-01 00:31 UTC, AHReccese approved these changes

2024-06-04 13:52 UTC, sepandhaghighi commented
@sadrasabouri, could you please rebase this PR and resolve any conflicts? Then ping me for the final review. 🔥

2024-06-10 08:06 UTC, sepandhaghighi requested changes
@sadrasabouri I think something went wrong during the rebase process. I can't see any changes in `meta.yml`.

2024-06-10 08:06 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `README.md` modified
Move this line to `Changed` section

2024-06-10 08:06 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `meta.yaml` modified
Move this line to `Changed` section

2024-06-11 15:55 UTC, sadrasabouri commented
> @sadrasabouri I think something went wrong during the rebase process. I can't see any changes in `meta.yml`.

`meta.yml` has been changed in [last PR](https://github.com/openscilab/pymilo/pull/104/files#diff-2bcb57e74c1bcda3739d1c3a6d835ef6b67b384403dfe6b1a8ef1eee742f590cR21-R23).

2024-06-14 11:48 UTC, sepandhaghighi approved these changes
LGTM 🚀

2024-06-14 11:50 UTC, merged