Docstrings
openscilab/pymilo pull request #118
Opened 2024-08-15 16:29 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-08-16 01:16 UTC, sadrasabouri requested changes
Thanks for your efforts. I left some comments.

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/communicator.py
> +        :return: str (the extracted decrypted version)
`:return: the extracted decrypted version`

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/compressor.py
> +    """The Pymilo DummyCompressor class is a dummy implementation of the Compressor interface to act as a simple wire."""
```
A dummy implementation of the Compressor interface.
```

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/encryptor.py
> +    """The Pymilo DummyEncryptor class is a dummy implementation of the Encryptor interface to act as a simple wire."""
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: str (compressed payload)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: str (extracted payload)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: str (encrypted payload)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: str (decrypted payload)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: Response object (varies based on the Implemented Protocol)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: Response object (varies based on the Implemented Protocol)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/interfaces.py
> +        :return: Response object (varies based on the Implemented Protocol)
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/pymilo_client.py
> +"""PyMiloClient for RESTFull protocol."""
`Protocol`

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/pymilo_client.py
> +    """The Pymilo PymiloClient class facilitates working with PyMiloServer."""
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/pymilo_server.py
> +"""PyMiloServer for RESTFull protocol."""
same

2024-08-16 01:16 UTC, sadrasabouri commented on pymilo/streaming/pymilo_server.py
> +    """The Pymilo PymiloServer class facilitates streaming the ML models."""
same

2024-08-16 01:16 UTC, sadrasabouri commented on tests/test_ml_streaming/run_server.py
> +communicator.run()
Add an extra line at the end of this file.

2024-08-16 12:33 UTC, AHReccese commented
@sadrasabouri Hi Sadra, Thank you for your comprehensive review, I will apply them all in the coming 4-5 hours.

2024-08-17 16:57 UTC, sadrasabouri approved these changes

2024-08-17 16:59 UTC, merged