autopep8.sh + minor refactorings
openscilab/pymilo pull request #124
Opened 2024-08-20 02:58 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-08-20 18:15 UTC, sadrasabouri requested changes
Thanks for your efforts. Minor comments requested.

2024-08-20 18:15 UTC, sadrasabouri commented on pymilo/streaming/communicator.py
> +        :return: boolean indicating successfulness of upload action
`True if upload was successful, False otherwise`

2024-08-20 18:15 UTC, sadrasabouri commented on pymilo/streaming/pymilo_client.py
> +            print("PyMiloClient failed to download the remote ML model.")
move printing strings to params.

2024-08-20 18:15 UTC, sadrasabouri commented on pymilo/streaming/pymilo_client.py
> +        print("PyMiloClient synched the local ML model with the remote one successfully.")
same.

2024-08-20 18:15 UTC, sadrasabouri commented on pymilo/streaming/pymilo_client.py
> +            print("PyMiloClient failed to upload the local model.")
same

2024-08-20 23:57 UTC, AHReccese commented
I will update `CHANGELOG.md` soon, review the rest.
@sadrasabouri

2024-08-22 00:33 UTC, sadrasabouri approved these changes
LGTM but introducing new methods should not be under refactoring PR.

2024-08-22 00:33 UTC, merged