Update/readme
openscilab/pymilo pull request #157
Opened 2024-11-20 00:48 UTC by AHReccese

#### Reference Issues/PRs
Update `README.md`
#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-11-20 00:49 UTC, AHReccese commented
@sepandhaghighi
Please check whether or not I need to add more details about this release works somewhere else.

2024-11-20 14:04 UTC, sepandhaghighi requested changes

2024-11-20 14:04 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `README.md` updated
Duplication (line `30`)

2024-11-20 14:04 UTC, sepandhaghighi commented on README.md
> +>>> communicator = PymiloServer(
Please avoid splitting lines when using `pycon` (Python Console) mode

2024-11-20 14:04 UTC, sepandhaghighi commented on README.md
> +>>> pymilo_client = PymiloClient(
Please avoid splitting lines when using `pycon` (Python Console) mode

2024-11-21 15:34 UTC, sepandhaghighi approved these changes
🔥

2024-11-21 15:47 UTC, merged