Version 0.3
openscilab/pymilo pull request #34
Opened 2023-09-23 15:32 UTC by AHReccese

#### Reference Issues/PRs
#18 
#### What does this implement/fix? Explain your changes.
Version 0.3 with the full support of scikit Decision Tree models prepared.
#### Any other comments?

2023-09-23 15:37 UTC, AHReccese commented
@sepandhaghighi 
Hi King Sepand, I hope you're feeling better today.
It is a tiny minor PR that mainly changes versions from `0.2` to `0.3`.
I suggest you kindly review this minor PR til 9/27/2023.

Thanks, AHR.

2023-09-25 15:49 UTC, sepandhaghighi requested changes

2023-09-25 15:49 UTC, sepandhaghighi commented on CHANGELOG.md
>  ### Added
Please remove this line

2023-09-25 15:49 UTC, sepandhaghighi commented on CHANGELOG.md
> +### Changed
Please remove this line too

2023-09-27 05:51 UTC, AHReccese commented on CHANGELOG.md
>  ### Added
Done.

2023-09-27 05:51 UTC, AHReccese commented on CHANGELOG.md
> +### Changed
Done.

2023-09-27 06:06 UTC, sepandhaghighi approved these changes
🚀

2023-09-27 06:07 UTC, merged