Clustering/kmeans
openscilab/pymilo pull request #35
Opened 2023-09-27 09:32 UTC by AHReccese

#### Reference Issues/PRs
#17 
#### What does this implement/fix? Explain your changes.
Add Clustering Chain
Add Kmeans(+test) support
Add Clustering purposed dataset and test
Add Clustering model's tests runner
Update `test_pymilo.py` and decouple the prediction from the pymiloing process(enhance the cohesiveness of pymiloing)
#### Any other comments?

2023-10-01 05:33 UTC, AHReccese commented
@sepandhaghighi
Hi, dear Sepand, I hope you're doing well, I suggest you review this major PR til 10/05/2023.
Although it is a major PR, it isn't complex that much.
I can explain the details whenever you want in our morning office times.

2023-10-07 16:53 UTC, sepandhaghighi requested changes
@AHReccese Thanks for your efforts 🔥 

1. Take a look at my comments
2. Please update `CHANGELOG.md`

2023-10-07 16:53 UTC, sepandhaghighi commented on pymilo/chains/clustering_chain.py
> +"""PyMilo chain for decision trees."""
decision trees?

2023-10-07 16:53 UTC, sepandhaghighi commented on SUPPORTED_MODELS.md
> +        <th>Category</th>
Please update this file 💯

2023-10-07 17:37 UTC, AHReccese commented on pymilo/chains/clustering_chain.py
> +"""PyMilo chain for decision trees."""
done.

2023-10-07 17:37 UTC, AHReccese commented on SUPPORTED_MODELS.md
> +        <th>Category</th>
done.

2023-10-13 13:17 UTC, AHReccese commented
@sepandhaghighi 
a kind reminder(since it is 4 days overdue(10 + 4 days), I know we're busy focusing on the proposal, but consider this reminder just as a commitment to the OSL guidelines.

2023-10-17 20:45 UTC, sepandhaghighi requested changes
@AHReccese Sorry for my late response 🔥 
Please take a look at my comments. Additionally, kindly update the `CHANGELOG.md` file. Thank you.

2023-10-17 20:45 UTC, sepandhaghighi commented on pymilo/utils/test_pymilo.py
>      :type test_data: np.ndarray or list
remove `test_data` from docstring

2023-10-17 20:45 UTC, sepandhaghighi commented on pymilo/utils/test_pymilo.py
> +    :param clusterer: the given clusterer model
wrong `docstring`

2023-10-20 23:43 UTC, sepandhaghighi approved these changes
🚀

2023-10-21 06:47 UTC, merged