Readme, Logo and Badges Added
openscilab/pymilo pull request #5
Opened 2023-02-27 21:49 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
A generic template for README.md will be added. This template contains a table of contents covering the necessary information for the readme page. Also, some badges are added right below the logo.

There are some commented parts that should be taken care of before the version 0.1 release.

2023-02-28 10:14 UTC, sepandhaghighi requested changes
Please take a look at my comments.
Also, resolve the conflicts 💯

2023-02-28 10:14 UTC, sepandhaghighi commented on README.md
> +    <img src="https://github.com/openscilab/pymilo/raw/master/otherfiles/logo.png">
add width="550"

2023-02-28 10:14 UTC, sepandhaghighi commented on README.md
> +  <!-- * [Scikit-learn](https://github.com/openscilab/pymilo#sciki-learn) -->
Remove comments

2023-02-28 10:14 UTC, sepandhaghighi commented on README.md
> +<!-- 3. Website : [https://www.ascii-art.site](https://www.ascii-art.site) -->
Remove comments

2023-02-28 10:14 UTC, sepandhaghighi commented on README.md
> +
Add code quality and CI tables. We will fill them later

2023-03-01 14:57 UTC, AHReccese commented
@sadrasabouri Great job Sadra.
I applied some tiny fixes:
1- One for centering the overview tables and 
2- the other one is to modify the name of the main branch referring to(main instead of master(which is the main in pycm :))).
Thanks.

2023-03-01 15:01 UTC, AHReccese approved these changes
LGTM

2023-03-01 18:57 UTC, sadrasabouri commented
> @sadrasabouri Great job Sadra. I applied some tiny fixes: 1- One for centering the overview tables and 2- the other one is to modify the name of the main branch referring to(main instead of master(which is the main in pycm :))). Thanks.

Great, thanks.

2023-03-02 11:33 UTC, sepandhaghighi commented
> @sadrasabouri Great job Sadra. I applied some tiny fixes: 1- One for centering the overview tables and 2- the other one is to modify the name of the main branch referring to(main instead of master(which is the main in pycm :))). Thanks.

@AHReccese 
Thanks for your efforts 💯 
I disagree with that centering personally. It would be better to align to the right because we will probably add some text there later.

2023-03-02 11:34 UTC, sepandhaghighi requested changes
@AHReccese take a look at my comments 📖

2023-03-02 14:24 UTC, AHReccese commented
rollbacked to left-aligned according to Sepand's suggestion.

2023-03-02 22:40 UTC, sepandhaghighi approved these changes
LGTM 💯

2023-03-02 22:41 UTC, merged