FeatureAgglomeration added to `pymilo_param.py`
openscilab/pymilo pull request #63
Opened 2023-12-31 11:46 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-01-02 20:23 UTC, sadrasabouri requested changes
Looks great. I left minor comments.

2024-01-02 20:23 UTC, sadrasabouri commented on tests/test_clusterings/test_clusterings.py
> +    "HIERARCHICAL_CLUSTERING":[agglomerative_clustering, feature_agglomeration],
`"HIERARCHICAL_CLUSTERING": [agglomerative_clustering, feature_agglomeration],`

2024-01-02 20:23 UTC, sadrasabouri commented on pymilo/utils/util.py
> +    :param module_name: module to import associated function from
`module to import the function from`

2024-01-02 20:23 UTC, sadrasabouri commented on pymilo/utils/util.py
> +    :param function_name: associated function's name to get imported
`function's name to get imported`

2024-01-03 00:45 UTC, AHReccese commented
I applied all of your comments, any other suggestion? 
@sadrasabouri

2024-01-03 02:07 UTC, sadrasabouri requested changes

2024-01-03 02:07 UTC, sadrasabouri commented on CHANGELOG.md
> +- `FeatureAgglomeration ` model
One extra space is inserted here.

2024-01-03 02:36 UTC, sadrasabouri approved these changes

2024-01-03 02:36 UTC, merged