Modern issue/feature template
openscilab/pymilo pull request #64
Opened 2024-01-02 21:24 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
Issue/bug report templates were in markdown format. This PR will update that template's format to `.yml` format.
Also, a separate feature request template is added.

2024-01-03 00:48 UTC, AHReccese approved these changes
Interesting update, thanks.

2024-01-03 04:32 UTC, AHReccese approved these changes

2024-01-05 22:36 UTC, sepandhaghighi requested changes
@sadrasabouri 🔥

2024-01-05 22:36 UTC, sepandhaghighi commented on otherfiles/RELEASE.md
> +9.  Close this version issues
Extra space?

2024-01-05 22:36 UTC, sepandhaghighi commented on otherfiles/RELEASE.md
> +4. Update `bug_report.yml`
I suggest using the full path:
`.github/ISSUE_TEMPLATE/bug_report.yml`

2024-01-06 22:01 UTC, sepandhaghighi approved these changes
🚀

2024-01-06 22:02 UTC, merged