Feature/naive bayes
openscilab/pymilo pull request #75
Opened 2024-01-21 09:35 UTC by AHReccese

#### Reference Issues/PRs
add support for 
- GaussianNaiveBayes
- MultinomialNaiveBayes
- ComplementNaiveBayes
- BernoulliNaiveBayes
- CategoricalNaiveBayes
#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-01-22 22:15 UTC, sadrasabouri requested changes
Thanks Amirhossein, I left minor. I hope they are useful.

2024-01-23 06:20 UTC, AHReccese commented on CHANGELOG.md
> +- LossFunctionTransporter enhanced to handle scikit 1.4.0 `_loss_function_` field.
It is needed because I forgot to add it in the last PR.

2024-01-23 06:20 UTC, AHReccese commented on CHANGELOG.md
> +- CategoricalNaiveBayes
Sure thing!

2024-01-23 06:26 UTC, AHReccese commented on pymilo/chains/naive_bayes_chain.py
> +    :type naive bayes: obj
when you read a json file, the output is a obj.

2024-01-23 06:28 UTC, AHReccese commented on pymilo/chains/naive_bayes_chain.py
> +    :type model: obj
no, not certainly, if the command is `serialize` then yes it is considered to be an instance of sklearn naive Bayes model, but when the command is `deserialize` then it is as I mentioned in the previous comment, it has `obj` type.

2024-01-23 06:28 UTC, AHReccese commented on pymilo/transporters/general_data_structure_transporter.py
> +                            # handle the case (2,29) in (2,)
removed.

2024-01-23 07:07 UTC, sadrasabouri commented on CHANGELOG.md
> +- LossFunctionTransporter enhanced to handle scikit 1.4.0 `_loss_function_` field.
`LossFunctionTransporter` enhanced to handle scikit 1.4.0 `_loss_function_` field

2024-01-23 07:13 UTC, sadrasabouri requested changes
Great. Just change the version 0.4 log to:
```
- `LossFunctionTransporter` enhanced to handle scikit 1.4.0 `_loss_function_` field
```

2024-01-23 08:29 UTC, AHReccese commented
> Great. Just change the version 0.4 log to:
> 
> ```
> - `LossFunctionTransporter` enhanced to handle scikit 1.4.0 `_loss_function_` field
> ```

Applied.

2024-01-23 08:30 UTC, sadrasabouri approved these changes
LGTM

2024-01-23 08:31 UTC, merged