Readme
openscilab/pymilo pull request #8
Opened 2023-06-14 03:01 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2023-06-14 05:59 UTC, sadrasabouri requested changes

2023-06-14 05:59 UTC, sadrasabouri commented on README.md
> +
I think it's better to remove this extra line.

2023-06-14 07:03 UTC, sadrasabouri approved these changes

2023-06-15 00:23 UTC, sepandhaghighi commented
@AHReccese Everything seems good here 💯 
But. now that `README.md ` is ready we need to add `version_check.py` script and add it to CI.
Take a look at this [link](https://github.com/sepandhaghighi/pycm/blob/master/Otherfiles/version_check.py)
We can leave it for another PR or handle it here. @sadrasabouri

2023-06-15 05:55 UTC, sadrasabouri commented
> @AHReccese Everything seems good here 100 But, now that `README.md ` is ready we need to add `version_check.py` script and add it to CI. Take a look at this [link](https://github.com/sepandhaghighi/pycm/blob/master/Otherfiles/version_check.py) We can leave it for another PR or handle it here. @sadrasabouri

I will handle it here ASAP.

2023-06-15 06:13 UTC, sadrasabouri commented
I updated `test.yml` and add `version_chek.py` + `meta.yaml`.
Please review it again guys @sepandhaghighi @AHReccese

2023-06-16 22:44 UTC, sepandhaghighi approved these changes

2023-06-16 22:45 UTC, merged