Version 0.6
openscilab/pymilo pull request #85
Opened 2024-03-25 08:25 UTC by AHReccese

#### Reference Issues/PRs
#79 #80 #81 
#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-03-25 13:31 UTC, sepandhaghighi requested changes
@AHReccese Take a look at my comment

2024-03-25 13:31 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `pymilo_obj.py` updated to use predefined strings.
remove `.`

2024-03-25 14:21 UTC, sepandhaghighi approved these changes
LGTM 🚀

2024-03-26 15:58 UTC, sadrasabouri approved these changes

2024-03-27 00:19 UTC, merged